// This file is licensed to you under the MIT license.
// See the LICENSE file in the project root for full license information.
// <autogenerated>

namespace Kangaroo.CodeGenerators.Structure
{
	using System;
	using System.Collections.Generic;
    using System.ComponentModel;
    using System.Text;
	using System.Xml.Serialization;

	[XmlRoot]
	public class CodeGeneratorSettings
	{
		[XmlElement]
		public EnumsSettings EnumsSettings { get; set; }

		[XmlElement]
		public BackendEntititesSettings BackendEntititesSettings { get; set; }
		
		[XmlElement]
		public FrontendEntititesSettings FrontendEntititesSettings { get; set; }

		[XmlElement]
		public DatabaseRepositoriesSettings DatabaseRepositoriesSettings { get; set; }

		[XmlElement]
		public ServicesSettings ServicesSettings { get; set; }

		[XmlElement]
		public APISettings APISettings { get; set; }

		[XmlElement]
		public APIClientSettings APIClientSettings { get; set; }
	}

	[XmlRoot]
	public class EnumsSettings
	{
		[XmlAttribute]
		public string EnumsNamespace { get; set; }
	}

	[XmlRoot]
	public class BackendEntititesSettings
	{
		[XmlAttribute]
		public string EntitiesNamespace { get; set; }

		[XmlAttribute]
		public string ValidatorsNamespace { get; set; }
	}

	[XmlRoot]
	public class FrontendEntititesSettings
	{
		[XmlAttribute]
		public string EntitiesNamespace { get; set; }

		[XmlAttribute]
		public string ValidatorsNamespace { get; set; }

		[XmlAttribute]
		[DefaultValue(true)]
		public bool GenerateNotifyPropertyChanges { get; set; } = true;
	}

	[XmlRoot]
	public class DatabaseRepositoriesSettings
	{
		[XmlAttribute]
		public string EntitiesNamespace { get; set; }

		[XmlAttribute]
		public string DatabaseEntitiesNamespace { get; set; }

		[XmlAttribute]
		public string DatabaseEntityTypeConfigurationNamespace { get; set; }

		[XmlAttribute]
		public string DbContextNamespace { get; set; }

		[XmlAttribute]
		public string DatabaseRepositoriesNamespace { get; set; }

		[XmlAttribute]
		public string DatabaseEntityMapperNamespace { get; set; }

		[XmlAttribute]
		[DefaultValue("Tb")]
		public string DatabaseEntityPrefix { get; set; } = "Tb";

		[XmlAttribute]
		[DefaultValue(true)]
		public bool GenerateDatabaseEntity { get; set; } = true;

		[XmlAttribute]
		[DefaultValue(true)]
		public bool GenerateDatabaseEntityTypeConfiguration { get; set; } = true;

		[XmlAttribute]
		[DefaultValue(true)]
		public bool GenerateDbContext { get; set; } = true;

		[XmlAttribute]
		[DefaultValue(true)]
		public bool UseIdentityDbContext { get; set; } = true;

		[XmlAttribute]
		public string IdentityDbContextCustomUserClass { get; set; }

		[XmlAttribute]
		[DefaultValue(true)]
		public bool GenerateDatabaseEntityMapper { get; set; } = true;
	}

	[XmlRoot]
	public class ServicesSettings
	{
		[XmlAttribute]
		public string DatabaseEntitiesNamespace { get; set; }

		[XmlAttribute]
		public string DatabaseRepositoriesNamespace { get; set; }

		[XmlAttribute]
		public string ServicesNamespace { get; set; }

		[XmlAttribute]
		[DefaultValue("Tb")]
		public string DatabaseEntityPrefix { get; set; } = "Tb";
	}

	[XmlRoot]
	public class APISettings
	{
		[XmlAttribute]
		public string ControllersNamespace { get; set; }

		[XmlAttribute]
		public string ServicesNamespace { get; set; }
	}

	[XmlRoot]
	public class APIClientSettings
	{
		[XmlAttribute]
		public string APIClientNamespace { get; set; }
	}
}