// This file is licensed to you under the MIT license.
// See the LICENSE file in the project root for full license information.
// <autogenerated>

namespace Kangaroo.CodeGenerators.Structure
{
	using System;
	using System.Collections.Generic;
    using System.ComponentModel;
    using System.Text;
	using System.Xml.Serialization;

	[XmlRoot]
	public class CodeGeneratorSettings
	{
		[XmlElement]
		public BackendEnumsSettings BackendEnumsSettings { get; set; }

		[XmlElement]
		public FrontendEnumsSettings FrontendEnumsSettings { get; set; }

		[XmlElement]
		public DatabaseRepositoriesSettings DatabaseRepositoriesSettings { get; set; }

		[XmlElement]
		public BackendEntititesSettings BackendEntititesSettings { get; set; }
		
		[XmlElement]
		public FrontendEntititesSettings FrontendEntititesSettings { get; set; }

		[XmlElement]
		public BackendCustomRequestsSettings BackendCustomRequestsSettings { get; set; }
		
		[XmlElement]
		public FrontendCustomRequestsSettings FrontendCustomRequestsSettings { get; set; }

		[XmlElement]
		public BackendCustomResponsesSettings BackendCustomResponsesSettings { get; set; }
		
		[XmlElement]
		public FrontendCustomResponsesSettings FrontendCustomResponsesSettings { get; set; }

		[XmlElement]
		public ServicesSettings ServicesSettings { get; set; }

		[XmlElement]
		public APISettings APISettings { get; set; }

		[XmlElement]
		public APIClientSettings APIClientSettings { get; set; }
	}

	[XmlRoot]
	public class BackendEnumsSettings
	{
		[XmlAttribute]
		public string EnumsNamespace { get; set; }
	}

	[XmlRoot]
	public class FrontendEnumsSettings
	{
		[XmlAttribute]
		public string EnumsNamespace { get; set; }
	}

	[XmlRoot]
	public class BackendEntititesSettings
	{
		[XmlAttribute]
		public string EntitiesNamespace { get; set; }

		[XmlAttribute]
		public string ValidatorsNamespace { get; set; }

		[XmlAttribute]
		[DefaultValue(true)]
		public bool GenerateIdentityEntities { get; set; } = true;
	}

	[XmlRoot]
	public class FrontendEntititesSettings
	{
		[XmlAttribute]
		public string EntitiesNamespace { get; set; }

		[XmlAttribute]
		public string ValidatorsNamespace { get; set; }

		[XmlAttribute]
		[DefaultValue(true)]
		public bool GenerateNotifyPropertyChanges { get; set; } = true;

		[XmlAttribute]
		[DefaultValue(true)]
		public bool GenerateIdentityEntities { get; set; } = true;
	}

	[XmlRoot]
	public class BackendCustomRequestsSettings
	{
		[XmlAttribute]
		public string CustomRequestsNamespace { get; set; }

		[XmlAttribute]
		public string ValidatorsNamespace { get; set; }
	}

	[XmlRoot]
	public class FrontendCustomRequestsSettings
	{
		[XmlAttribute]
		public string CustomRequestsNamespace { get; set; }

		[XmlAttribute]
		public string ValidatorsNamespace { get; set; }

		[XmlAttribute]
		[DefaultValue(true)]
		public bool GenerateNotifyPropertyChanges { get; set; } = true;
	}

	[XmlRoot]
	public class BackendCustomResponsesSettings
	{
		[XmlAttribute]
		public string CustomResponsesNamespace { get; set; }

		[XmlAttribute]
		public string ValidatorsNamespace { get; set; }
	}

	[XmlRoot]
	public class FrontendCustomResponsesSettings
	{
		[XmlAttribute]
		public string CustomResponsesNamespace { get; set; }

		[XmlAttribute]
		public string ValidatorsNamespace { get; set; }

		[XmlAttribute]
		[DefaultValue(true)]
		public bool GenerateNotifyPropertyChanges { get; set; } = true;
	}

	[XmlRoot]
	public class DatabaseRepositoriesSettings
	{
		[XmlAttribute]
		public string DbContextNamespace { get; set; }
		
		[XmlAttribute]
		public string DatabaseEntitiesNamespace { get; set; }

		[XmlAttribute]
		public string DatabaseEntityTypeConfigurationNamespace { get; set; }

		[XmlAttribute]
		public string DatabaseRepositoriesNamespace { get; set; }

		[XmlAttribute]
		public string DatabaseEntityMapperNamespace { get; set; }

		[XmlAttribute]
		public string EntitiesNamespace { get; set; }

		[XmlAttribute]
		[DefaultValue("Tb")]
		public string DatabaseEntityPrefix { get; set; } = "Tb";

		[XmlAttribute]
		[DefaultValue(true)]
		public bool GenerateDatabaseEntity { get; set; } = true;

		[XmlAttribute]
		[DefaultValue(true)]
		public bool GenerateDatabaseEntityTypeConfiguration { get; set; } = true;

		[XmlAttribute]
		[DefaultValue(true)]
		public bool GenerateDbContext { get; set; } = true;

		[XmlAttribute]
		[DefaultValue(true)]
		public bool UseIdentityDbContext { get; set; } = true;

		[XmlAttribute]
		public string IdentityDbContextCustomUserClass { get; set; }

		[XmlAttribute]
		[DefaultValue(true)]
		public bool GenerateDatabaseEntityMapper { get; set; } = true;
	}

	[XmlRoot]
	public class ServicesSettings
	{
		[XmlAttribute]
		public string DbContextNamespace { get; set; }

		[XmlAttribute]
		public string DatabaseEntitiesNamespace { get; set; }

		[XmlAttribute]
		public string DatabaseRepositoriesNamespace { get; set; }

		[XmlAttribute]
		public string EntitiesNamespace { get; set; }

		[XmlAttribute]
		public string ServicesNamespace { get; set; }

		[XmlAttribute]
		[DefaultValue("Tb")]
		public string DatabaseEntityPrefix { get; set; } = "Tb";

		[XmlAttribute]
		[DefaultValue("")]
		public string GenerateIdentityServiceBasedOnCustomUserClass { get; set; } = string.Empty;
	}

	[XmlRoot]
	public class APISettings
	{
		[XmlAttribute]
		public string ControllersNamespace { get; set; }

		[XmlAttribute]
		public string ServicesNamespace { get; set; }

		[XmlAttribute]
		public string EntitiesNamespace { get; set; }

		[XmlAttribute]
		[DefaultValue(true)]
		public bool GenerateIdentityController { get; set; } = true;
	}

	[XmlRoot]
	public class APIClientSettings
	{
		[XmlAttribute]
		public string APIClientNamespace { get; set; }

		[XmlAttribute]
		public string EntitiesNamespace { get; set; }

		[XmlAttribute]
		[DefaultValue(true)]
		public bool GenerateIdentityAPIClient { get; set; } = true;
	}
}